### ISSUE TITLE
f-droid version outdated 

### ISSUE THREAD

**Issue by BalooUriza** [servalproject/batphone#103]
Looks like Google Play and F-Droid are out of synch.

**Comment by marclaporte** [comment]
Given the nice enhancements in 0.92, it would be really awesome to have in F-Droid.

Thanks!

**Comment by breversa** [comment]
Agreed !
(Is there any way to star that issue ? :-) )

**Comment by lakeman** [comment]
See https://f-droid.org/forums/topic/serval-batphone/

**Comment by krt16s** [comment]
Ref: https://github.com/servalproject/batphone/issues/109

**Comment by axelsimon** [comment]
Please close issue.

F-droid currently [reports](https://f-droid.org/packages/org.servalproject/):
> Version 0.93 (2371) - Added on 2017-06-03
