### ISSUE TITLE
Is there an easy way to generated unsigned release binaries?

### ISSUE THREAD

**Issue by krt16s** [servalproject/batphone#109]
Our current setup at f-droid.org handles signing on it's own and doesn't hand that over to the individual gradle or ant build tools. Is there an easy (without tampering with the build files) way to generated unsigned release binaries? Maybe a ant target that I've missed?

**Comment by lakeman** [comment]
We've overridden the normal release target to add our own wrapper around
the android signing process. We then call the normal android build process
through the target name android_rules.release. You might be able to do the
same from the command line.

**Comment by ildar** [comment]
verdict?

**Comment by lakeman** [comment]
Works for me;
$ ant android_rules.release
