### ISSUE TITLE
No builds of 0.93 available on Google Play or F-Droid

### ISSUE THREAD

**Issue by rodneyrod** [servalproject/batphone#112]

**Comment by lakeman** [comment]
You have to opt in to alpha or beta builds on the play store here; https://play.google.com/apps/testing/org.servalproject.
Getting alpha builds this way requires that you are a member of our google group serval-project-developers@googlegroups.com.
0.93-pre-44-g22f76dd was uploaded to the play store on Jan 12th.

We haven't tagged any beta ( / release candidate) builds of 0.93 yet. 

We don't have any involvement with F-Droid, they build our software themselves.

**Comment by rodneyrod** [comment]
Okay, looks like F-Droid won't import any changes unless releases are tagged.

You think it would be possible to update this? 0.92 is quite old.
