### ISSUE TITLE
Master has errors in build but development is fine

### ISSUE THREAD

**Issue by DingoOz** [servalproject/batphone#113]
I am a new developer - apologies if already handled. I am developing on Ubuntu 15.04.

The build instructions work fine for development branch but I got errors with master. 
Errors related to undefined symbols, including version numbers.

**Comment by lakeman** [comment]
master is what we shipped in 0.92. It's not going to be patched until we
release 0.93.

That said;
Make sure jni/serval-dna is the right commit, the API between these two
components changes fairly often.
Once your environment is setup, build using "$ ant debug". That's the only
thing we really support.

And if you want more suggestions, seeing your actual error log is mandatory.

**Comment by DingoOz** [comment]
Thanks for the super prompt reply. That makes sense.

Hopefully this post can help anyone else if they struggle on getting master to build as per the wiki instructions...  

I am quite happy to play in development, and am happy as a pig in mud as it compiles happily for me.
