### ISSUE TITLE
Command keyring add returned an error

### ISSUE THREAD

**Issue by fhteagle** [servalproject/batphone#116]
New install of serval via Google play store (serval version unknown because I cannot actually get into the app). Installing on Motorola XT1575 with OEM Android 6.0. 

When I press the setup wizard button, the title of this bug is displayed as a toast message. The app does proceed to the Set a number and display name screen, but I cannot get past that screen. When pressing "OK" on that screen, I get:

"Attempt to invoke virtual method void org.servalproject.servald.identity.setdetails (Android.Content.Context, Java.lang.string, Java.lang.string) on a null object reference"

The app will not proceed past the set a number screen.

**Comment by lakeman** [comment]
Sounds like you are using the current play store version; 0.92. There may be more specific details of the underlying issue output to the android log.

However this code has been completely replaced in the current development version. You can test with the latest alpha build by joining our google group and opting in to testing. More info here;
http://developer.servalproject.org/dokuwiki/doku.php?id=content:servalmesh:google_play_testing
