### ISSUE TITLE
Importing the project

### ISSUE THREAD

**Issue by jaylakhani** [servalproject/batphone#118]
I need to use  serval batphone in my project.
But I don't have any idea how to import this project
I searched the Internet and it said you need build.gradle file but it is not present in the file.
I need to know the way of importing this project
Please do the need.

**Comment by lakeman** [comment]
We don't support using android studio or gradle to build our apk, instead
you should follow the instructions in Install.md.
You can use android studio as an editor for the java classes and other
android artifacts.
