### ISSUE TITLE
incompatible API use in your code.

### ISSUE THREAD

**Issue by jay2013** [servalproject/batphone#135]
Hi, we find that constructor of Class String <java.lang.String: void <init>(byte[],int,int,java.nio.charset.Charset)> no exist in SDK level 8, the documentation of SDK change says it is added in level 9. 

However, in your source code, you called this api in method <org.servalproject.system.bluetooth.BlueToothControl: java.lang.String encodeName(byte[])>.
We notice that your app's minSDKVersion is 8. so it will be a bug when others run your app on a mobile device with sdk level 8. 

BUG Detail:
<java.lang.String: void <init>(byte[],int,int,java.nio.charset.Charset)> called in <org.servalproject.system.bluetooth.BlueToothControl: java.lang.String encodeName(byte[])> on line 399 not in [8]

please help to check. Thanks very much.

Dongjie He

**Comment by lakeman** [comment]
Simple enough to fix. But I haven't seen any crash bugs from this.

**Comment by jay2013** [comment]
Maybe few people now use a mobile device with such an old android version!
