### ISSUE TITLE
git submodule error

### ISSUE THREAD

**Issue by monster-xie** [servalproject/batphone#140]
$ git submodule -q update
error: no such remote ref 53e25ae8e508e30415c9ba5b8abb45961dd23f52
Fetched in submodule path 'app/src/main/jni/libsodium', but it did not contain 53e25ae8e508e30415c9ba5b8abb45961dd23f52. Direct fetching of that commit failed.

**Comment by lakeman** [comment]
We've mirrored all of the libsodium commits we've ever used in https://github.com/servalproject/libsodium. Add that as a remote and you should be able to fetch and check it out.
