### ISSUE TITLE
serval-dna clone  error!

### ISSUE THREAD

**Issue by monster-xie** [servalproject/batphone#143]
When i clone the libsodium branche ,according to the install.md instruction to set environment.
But when i execute the build_setup.sh,repot error:
Cloning into 'jni/serval-dna'...
remote: Counting objects: 24347, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 24347 (delta 28), reused 52 (delta 22), pack-reused 24267
Receiving objects: 100% (24347/24347), 29.46 MiB | 140.00 KiB/s, done.
Resolving deltas: 100% (15841/15841), done.
Checking connectivity... done.
fatal: reference is not a tree: c8ecb831f78ef0a3547b463428891a58cb867d6a
Unable to checkout 'c8ecb831f78ef0a3547b463428891a58cb867d6a' in submodule path 'jni/serval-dna'
monster@monster-VirtualBox:/usr/local/xie/batphone$ git submodule 
 0fe8fc39c75b5a6865f52e20e557d15e36c3dbe9 jni/libsodium (0fe8fc39)
+f91033820bea8d108f27660a22775f627275e516 jni/serval-dna (heads/development)

**Comment by lakeman** [comment]
Dupe #140, add the remote to the submodule .git/config
