### ISSUE TITLE
ant debug error!

### ISSUE THREAD

**Issue by monster-xie** [servalproject/batphone#144]
When i finish the build_setup.sh,the execute the ant debug command.report error:

@ubuntu:~/smartphone/batphone$ ant debug
Buildfile: /home/whitefly/smartphone/batphone/build.xml

BUILD FAILED
/home/whitefly/smartphone/batphone/build.xml:78: Expected to find libsodium.a.
Have you run ./build_setup?
Refer to INSTALL.md for more information.

Total time: 1 second

**Comment by lakeman** [comment]
We migrated the development branch to a gradle build process some time ago. 
Provided you checkout the development branch and have the right libsodium remote, the gradle build should be quite painless.

**Comment by monster-xie** [comment]
I am in the libsodium branch.
