### ISSUE TITLE
Android phone app uses up the battery quickly

### ISSUE THREAD

**Issue by petterreinholdtsen** [servalproject/batphone#91]
The android phone app reduces the life time of the phone quite a lot when it is running in the background.  Can something be done to reduce the power consumption?

**Comment by lakeman** [comment]
As of ba68c736, battery usage should be much lower. Though there is still room for improvement as an ongoing activity.

**Comment by petterreinholdtsen** [comment]
Great to hear. When you measure, by how much does this new patch extend battery lifetime?

**Comment by lakeman** [comment]
So far I've only performed one long test, which showed a 1% duty cycle when the network was up, but there were no detected network peers. In this case, the battery should last 100x longer (in theory).
More details;
https://groups.google.com/d/msg/serval-project-developers/vrs4ly11ZOA/3DSc9ZJV3aMJ
